server:
  port: 8080

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/spa-booking

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://spa-user-service:8082
          predicates:
            - Path=/me/**

        # Public read examples (sau n√†y)
        - id: catalog-public
          uri: http://spa-catalog-service:8083
          predicates:
            - Path=/services/**

management:
  endpoints:
    web:
      exposure:
        include: health,info
