spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          # Cloud: thường Keycloak chạy trong cluster hoặc có domain public/private ổn định
          jwk-set-uri: ${KEYCLOAK_JWKS_URI}

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: ${USER_SERVICE_URL:http://spa-user-service:8082}
          predicates:
            - Path=/user/**

        - id: catalog-service
          uri: ${CATALOG_SERVICE_URL:http://spa-catalog-service:8083}
          predicates:
            - Path=/catalog/**
