spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://spa-user-service:8082
          predicates:
            - Path=/api/v1/user/**

        - id: catalog-service
          uri: http://spa-catalog-service:8083
          predicates:
            - Path=/api/v1/catalog/**
