spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          # local fetch JWKS trực tiếp từ localhost
          jwk-set-uri: ${KEYCLOAK_JWKS_URI:http://localhost:18081/realms/spa-booking/protocol/openid-connect/certs}

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: ${USER_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/user/**

        - id: catalog-service
          uri: ${CATALOG_SERVICE_URL:http://localhost:8083}
          predicates:
            - Path=/catalog/**
